### PR TITLE
Typescript support

### PR DESCRIPTION
**Pull request by MiguelMadero**
When I try to use it on typescript it says the transformation only works for JS. I tried this after changing the language mode to JS and it works jus fine. 

This will likely work the same for flow, but I'm not familiar enough to test it.

### CODE REVIEW

**Comment by angryobject** [comment]
I'm not familiar with TS myself, are you sure that there are no cases where it will fail due to some TS magic, e.g. type declarations, different syntax etc.?  Because jscodeshift works with JS, not TS.

I think if we do this we need to add some tests in TS to ensure everything is fine. I might look into this once I have time.

**Comment by angryobject** [comment]
Sorry, I can't merge this now, because recast and jscodeshift don't support TS yet. There issues opened in their repos, but until they are done, we can't do it. It probably works in some cases (like you had), but we can't rely on it.

https://github.com/benjamn/recast/issues/424
https://github.com/benjamn/ast-types/issues/213
https://github.com/facebook/jscodeshift/issues/180

**Comment by MiguelMadero** [comment]
👍 thanks for looking into it and sorry for not replying earlier.

**Comment by angryobject** [comment]
You can now set `reactPureToClass.typescript` setting to `true` to enable ts files support. But it comes with no guarantees =)

**Pull request closed without merging**
